Repository RobbieTheWagner/ember-flatpickr, pull requests merged in 2020-08, with the labels that each got.

#499 Support no locales
  index.js
Labels: enhancement

#508 Ember 3.20
  .eslintrc.js
  .travis.yml
  config/ember-try.js
  package.json
  tests/dummy/app/app.js
  tests/dummy/app/router.js
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/targets.js
  tests/test-helper.js
  yarn.lock
Labels: enhancement

#513 Remove Mixin, refactor to glimmer component
  .travis.yml
  README.md
  addon/components/ember-flatpickr.hbs
  addon/components/ember-flatpickr.js
  addon/mixins/flatpickr.js
  config/ember-try.js
  package.json
  tests/dummy/app/controllers/docs/components/ember-flatpickr.js
  tests/dummy/app/templates/docs/components/ember-flatpickr.md
  tests/dummy/app/templates/docs/usage.md
  tests/integration/components/ember-flatpickr-test.js
  tests/unit/mixins/flatpickr-test.js
  yarn.lock
Labels: breaking

#514 Remove `getFlatpickrRef` and `appendDataInput`, update flatpickr to 4.6.6
  addon/components/ember-flatpickr.js
  package.json
  tests/dummy/app/templates/docs/components/ember-flatpickr.md
  tests/dummy/app/templates/docs/usage.md
  tests/integration/components/ember-flatpickr-test.js
  yarn.lock
Labels: breaking

#515 Prettier fixes, remove power-select styles, cleanup
  .prettierrc.js
  addon/components/ember-flatpickr.hbs
  addon/components/ember-flatpickr.js
  app/styles/app.scss
  config/ember-try.js
  tests/.eslintrc.js
  tests/dummy/app/styles/app.scss
  tests/dummy/app/templates/docs/components/ember-flatpickr.md
  tests/dummy/app/templates/docs/usage.md
Labels: internal
